version: "3.8"
volumes:
  db-store:
  php-fpm-socket:
services:

  php:
    container_name: php
    build: ./docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../src/yii:/work/backend

  nginx-php:
    container_name: nginx-php
    build: ./docker/nginx-php
    ports:
      - 9000:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../src/yii:/work/backend
      - ./docker/nginx-php/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  nginx-proxy:
    container_name: nginx-proxy
    build: ./docker/nginx-proxy
    ports:
      - 80:80
    volumes:
      - ./docker/nginx-proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    

  nuxt:
    container_name: nuxt
    build:
      context: ./docker/nuxt
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../src/nuxt:/src:cached
      # exclude volumes
      - /src/app/node_modules
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true

